
name: Checking Markdown
description: Check if links in markdown files are functional

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Install and run npm
      shell: bash
      run: |
        npm install -g markdown-link-check
        markdown-link-check --version
        find . -name \*.md  -print0  | xargs -0 -n1 markdown-link-check -c $GITHUB_ACTION_PATH/config.json -a 403,200
